In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
x = np.array( [ [5,3] , 
                [10,15] , 
               [85,70],
              [71,80],
              [15,12] ,
              [24,10],
              [30,30],
              
              [60,80],
              [70,55],
              [80,90] 
#                ,
#                [150,150],
#                [148,148] ,
#                [152,152] ,
#                [150,148],
#                [148,150],
#                [150,152],
#                [152,150]
              ])

In [3]:
DTM = pd.DataFrame( x , columns = ['t1','t2'] )
DTM.head(2)

t1  t2
0   5   3
1  10  15

In [9]:
from sklearn.cluster import KMeans

kmeans = KMeans( n_clusters = 2 , random_state = 0 )
y_means = kmeans.fit_predict( x )

In [10]:
DTM['cluster'] = y_means

In [11]:
DTM.head(2)

t1  t2  cluster
0   5   3        0
1  10  15        0

In [12]:
kmeans.cluster_centers_

array([[16.8, 14. ],
       [73.2, 75. ]])

In [35]:
# From cluster center we will be able to find the dominating term in that cluster

# (16,8 , 14.0) is the cluster center of one cluster
# (73.2 , 74.8) is the cluster center of another cluster

# In first cluster : the centroid of T1 is at 16.8 and centroid of t2 is 14.0 , these are nothing but arithmetic means
    
# This means the average of all the t1 frequencies of all documents ins cluster - 1 is 16.8 and t2 is 14

# 16.8 > 14

# T1 is more dominating than T2 in cluster 1
# T2 is more dominating than T1 in Cluster 2

In [80]:
c_center = kmeans.cluster_centers_
c_center

array([[73.2, 75. ],
       [16.8, 14. ]])

In [81]:
c_center_l =  [ list( enumerate(i)) for i in c_center ]
c_center_l

[[(0, 73.2), (1, 75.0)], [(0, 16.8), (1, 14.0)]]

In [91]:
def n_high( c_center , n ) :
    c_center_l =  [ list( enumerate(i)) for i in c_center ]
    c_center_l1 = [sorted( i  , reverse = True , key = lambda x : (x[1],x[0]))  for i in c_center_l ]
    for i in c_center_l1 :
        print( " The n highest term of cluster " )
        for j in range( n ):
            print( BOW[ i[j][0] ]  )
            
n_high( l ,  1 )

 The n highest term of cluster 
D
 The n highest term of cluster 
camera


In [106]:
BOW = ['battery' , 'camera' , 'D']
BOW

['battery', 'camera', 'D']

In [123]:
def n_high( c_center , n ) :
    x = np.argsort( l , axis = 1   )
    print(x )
    x_sort = x[ : , : : -1 ]
    print( x_sort )
    for i in x_sort :
        print( " The n terms of the first cluster : ")
        for j in i[ : n ]:
            print( BOW[j])
            
n_high( l ,  2 )

[[0 1 2]
 [0 2 1]]
[[2 1 0]
 [1 2 0]]
 The n terms of the first cluster : 
D
camera
 The n terms of the first cluster : 
camera
D


In [101]:
x[0][2]

2

In [119]:
l = np.array( [ [1,2,3] , [3,12,5] ] )
l

array([[ 1,  2,  3],
       [ 3, 12,  5]])

In [77]:
np.argsort?

In [92]:
np.argsort( l , axis = 1   ) 

array([[0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [71]:
[ sorted(i,reverse = True ) for i in np.argsort( l , axis = 1   ) ]

[[2, 1, 0], [2, 1, 0]]

In [54]:
l1 = [ list( enumerate(i)) for i in l ]
l1

[[(0, 1), (1, 2), (2, 3)], [(0, 3), (1, 12), (2, 5)]]

In [55]:
[sorted( i  , reverse = True )  for i in l1]

[[(2, 3), (1, 2), (0, 1)], [(2, 5), (1, 12), (0, 3)]]